export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const PURCHASE = 'PURCHASE';
export const PURCHASE_CANCEL = 'PURCHASE_CANCEL';
export const PURCHASE_CONTINUE = 'PURCHASE_CONTINUE';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
